### ISSUE TITLE
how to train on custmer dataset?

### ISSUE THREAD

**Issue by bitwangdan** [YueLiao/PPDM#10]
Thank you for sharing the code. I trained on my own dataset(two object, six verb), but my output value is like this. Is there something wrong with my Settings?
![image](https://user-images.githubusercontent.com/18326564/78961654-cf966300-7b24-11ea-8d8d-a151250ae0d0.png)
@YueLiao

**Comment by YueLiao** [comment]
I cannot make sure whether it is wrong only based on this confidence map. You can evaluate the results by modifying the evaluation script for your dataset or visualize the predictions.

**Comment by bitwangdan** [comment]
@YueLiao i have changed the num_class(two) and the num_verbs(six)，my final eval result is like this, 
![image](https://user-images.githubusercontent.com/18326564/78967475-2ad05180-7b35-11ea-8222-f9a5e239fdd6.png)
can you share you model trained with hico dataset?

**Comment by YueLiao** [comment]
The result may be wrong. I have trained our method for a dataset with 10 classes, and the mAP is about 70%.  You should carefully check the code in hico.py, hico_eval.py, decode.py, hoidet.py, etc, and make sure all right for your own dataset.
