### ISSUE TITLE
the relationship of subject_id and object_id

### ISSUE THREAD

**Issue by zhazhazhazhi** [YueLiao/PPDM#12]
I can't understand the relationship of this subject_id  and  object_id in your test_hico.json file. Whether there is a word list, can be one-to-one correspondence.  

test_hico.json
what is means in the subject_id , object_id .  What do the numbers inside mean?   
Thank you

**Comment by YueLiao** [comment]
Hi, the subject_id and object_id is the index of the box annotations list. I have found the conventional annotation file is hard to understand, and I plan to update the annotation file recently.

**Comment by zhazhazhazhi** [comment]
thanks for your reply. I  understand it , but i still have a problem. for example  the bbox is the cup( category_id is 4), 4 Is it a cup?  I find that the list of coco  is't a cup .   can you give us a list for object . Let the detected people and object have a word list where the ID can be found .

**Comment by YueLiao** [comment]
coco_class_dict={1: 'person', 2: 'bicycle', 3: 'car', 4: 'motorcycle', 5: 'airplane', 6: 'bus', 7: 'train', 8: 'truck', 9: 'boat', 10: 'traffic light', 11: 'fire hydrant', 13: 'stop sign', 14: 'parking meter', 15: 'bench', 16: 'bird', 17: 'cat', 18: 'dog', 19: 'horse', 20: 'sheep', 21: 'cow', 22: 'elephant', 23: 'bear', 24: 'zebra', 25: 'giraffe', 27: 'backpack', 28: 'umbrella', 31: 'handbag', 32: 'tie', 33: 'suitcase', 34: 'frisbee', 35: 'skis', 36: 'snowboard', 37: 'sports ball', 38: 'kite', 39: 'baseball bat', 40: 'baseball glove', 41: 'skateboard', 42: 'surfboard', 43: 'tennis racket', 44: 'bottle', 46: 'wine glass', 47: 'cup', 48: 'fork', 49: 'knife', 50: 'spoon', 51: 'bowl', 52: 'banana', 53: 'apple', 54: 'sandwich', 55: 'orange', 56: 'broccoli', 57: 'carrot', 58: 'hot dog', 59: 'pizza', 60: 'donut', 61: 'cake', 62: 'chair', 63: 'couch', 64: 'potted plant', 65: 'bed', 67: 'dining table', 70: 'toilet', 72: 'tv', 73: 'laptop', 74: 'mouse', 75: 'remote', 76: 'keyboard', 77: 'cell phone', 78: 'microwave', 79: 'oven', 80: 'toaster', 81: 'sink', 82: 'refrigerator', 84: 'book', 85: 'clock', 86: 'vase', 87: 'scissors', 88: 'teddy bear', 89: 'hair drier', 90: 'toothbrush'}

**Comment by zhazhazhazhi** [comment]
think you

**Comment by deep-practice** [comment]
'hoi_annotation': [{'subject_id': 1, 'object_id': 0, 'category_id': 5}, {'subject_id': 1, 'object_id': 0, 'category_id': 7}]

HOIW数据集里面的subject_id取值有哪些呢？ @YueLiao

**Comment by mytk2012** [comment]
Does subject_id refer to person?Otherwise, we can assign person label to subject_id or object_id?
