### ISSUE TITLE
socket.gaierror: [Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by fengqi1996** [YueLiao/PPDM#15]
When I run the main.py, I get the error.
How can I fix it? My server cannot connect to the internet.
<img width="1778" alt="QQ20200629-163550@2x" src="https://user-images.githubusercontent.com/37800098/85992053-ed3ddf00-ba26-11ea-80c0-52893616d52b.png">

**Comment by YueLiao** [comment]
You can download the pre-train model offline and put it into  $HOME/.torch/model/ .
