### ISSUE TITLE
Humble request for supportive files for V-COCO dataset

### ISSUE THREAD

**Issue by BozhouZha** [YueLiao/PPDM#17]
Hi YueLiao,

I'm so sorry for bothering you again. I wondered may I have the "corre_vcoco.npy" file if it's at your convenience? I found that just like the hico dataset, the program also relies on the binary mask to do the validation or testing. Annotation alone cannot bring me there. Thank you in advance!

Bozhou

**Comment by YueLiao** [comment]
You can generate the "npy" by yourself following the below rules: The "corre_*.npy" is generated by the "train_*.json" annotation file. If an interaction is defined between ith class object and jth verb, the value at location (i,j) of "corre_*.npy" is 1 else 0.

**Comment by BozhouZha** [comment]
> You can generate the "npy" by yourself following the below rules: The "corre__.npy" is generated by the "train__.json" annotation file. If an interaction is defined between ith class object and jth verb in training set, the value at location (i,j) of "corre_*.npy" is 1 else 0.

Thanks, I'll try it out. Have a good one~

**Comment by BozhouZha** [comment]
> You can generate the "npy" by yourself following the below rules: The "corre__.npy" is generated by the "train__.json" annotation file. If an interaction is defined between ith class object and jth verb in training set, the value at location (i,j) of "corre_*.npy" is 1 else 0.


Hi YueLiao,

Thanks again for the way you pointed out yesterday. But I'm still trying to figure the mask out. I'm a newbie at this so this might be a dumb question: 

The "i-th" and "j-th" you mentioned is not likely the numerical category label of the object and the verb, right? Take the object for example, the largest categorical index is 90 but the shape of the corre_hico is <117, 80>, which means 80 masks available for object series. It makes sense since some objects are not documented and the faultage exists in those 90 indices.

So I wonder which kind of mapping I'm supposed to be using? I guess there might be a list of unordered category ids for the objects and verbs respectively, and the index of the items is the exactly "i" & "j" you mentioned.

I appreciate your help so much!

**Comment by YueLiao** [comment]
You can map the 90 categories into 80 categories through the label list in dataset/hico.py first, then generating the corre.npy

**Comment by BozhouZha** [comment]
> You can map the 90 categories into 80 categories through the label list in dataset/hico.py first, then generating the corre.npy

Get, thanks bro!
