### ISSUE TITLE
HOI-A dataset

### ISSUE THREAD

**Issue by tamtamz** [YueLiao/PPDM#18]
Thank you for sharing your great work! I have been working on human object interaction detection and want to evaluate our algorithm with HOI-A dataset. When are you going to release it? I hope you will be able to provide the information.

**Comment by YueLiao** [comment]
Thanks for your interest in our works. The official version of HOI-A is still refining now. You can use the HOI-W dataset (a coarse version of HOI-A dataset) as a replacement now. More about HOI-A and HOI-W can be seen in #8

**Comment by tamtamz** [comment]
Thanks! I will use HOI-W.
