### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by WinstonDeng** [YueLiao/PPDM#20]
Hi, thanks for your work.
There is an error when testing a pre-trained model:
```
Traceback (most recent call last):
  File "test_hoi.py", line 112, in <module>
    prefetch_test(opt)
  File "test_hoi.py", line 98, in prefetch_test
    map = hoi_eval.evalution(output_hoi)
  File "PPDM/src/lib/eval/hico_eval.py", line 62, in evalution
    bbox_pairs, bbox_ov = self.compute_iou_mat(gt_bbox, pred_bbox)
ValueError: not enough values to unpack (expected 2, got 0)
```
And it's ok if I test without '--test_with_eval'. Do you have any advice?

**Comment by YueLiao** [comment]
Hi, I cannot know what happens based on this error. I suggest that you can debug the code with Pdb or a certain IDE and provide more information for me to solve this problem.

**Comment by WinstonDeng** [comment]
@YueLiao Hi, I print the value of **pred_i['predictions']**, is **0**, where image name is **HICO_test2015_00000001.jpg**.
![图片](https://user-images.githubusercontent.com/38663473/89510645-6937fd80-d803-11ea-95f4-7429e4ea9888.png)
It looks like that no object is detected by model.

**Comment by YueLiao** [comment]
It must be some wrong. You may need to carefully check the environment.

**Comment by WinstonDeng** [comment]
My env info:

> Ubuntu 16.04.6 LTS
> Pytorch 0.4.1
> opencv-python             4.0.0.21
> Cython                    0.29.21
> numba                     0.50.1
> progress                  1.5
> easydict                  1.9
> scipy                     1.1.0

**Comment by WinstonDeng** [comment]
@YueLiao The reason is that I forgot to set "--arch=hourglass" when testing corresponding model. 
Sorry for my stupid question. And thanks for your patient reply.
