### ISSUE TITLE
HOI-A dataset

### ISSUE THREAD

**Issue by NguyenVanThanhHust** [YueLiao/PPDM#21]
Could you publish HOI-A dataset? I see on your paper and github, you already publish your result. But you haven't published your dataset yet. 
If you publish dataset, please publish it on google drive/one drive because baidu required sigh up and it doesn't send message to VN.

**Comment by YueLiao** [comment]
Here is the OneDrive download link.

https://sensetime-my.sharepoint.cn/:f:/g/personal/liaoyue_sensetime_com/EkUA1sc_sHNNmVNiVsyF8L0BpXlNm96I2orJY44Y4At3Rw?e=hn2Y3A

You may need to copy the address into the browser instead of clicking on the link directly.

**Comment by NguyenVanThanhHust** [comment]
Thank you.

**Comment by llrebecca** [comment]
Hi, where can I get train_hoia.json and test_hoi.json? The above link only has trainval.json. Thanks a lot!
