### ISSUE TITLE
Question about multi-person case

### ISSUE THREAD

**Issue by WinstonDeng** [YueLiao/PPDM#22]
Hi, 
the **size** of object heatmap is `[num_class, output_h, output_w]` in your code. 
Does it mean that the heatmap **can not classify different person** due to `catorgry_id=1`?
If not, how to address multi-person case?
e.g. image [`COCO_train2014_000000210751.jpg`]:
![图片](https://user-images.githubusercontent.com/38663473/90396728-4d690d00-e0c9-11ea-8236-128fe7ce4c91.png)

**Comment by YueLiao** [comment]
Our model must be able to process the "multi-person" case. There may be a lots of peaks in the human heatmap, and we will select the topK locations.

**Comment by WinstonDeng** [comment]
Thanks for your help!
