### ISSUE TITLE
main architecture of network

### ISSUE THREAD

**Issue by mahsa1363** [YueLiao/PPDM#23]
Hello
thanks for your code
Where is the ground truth point heatmap file?
I dont understand your code. In which file is there Point Detection Branch file and Point matching branch ؟
In which code is the main architecture of your network and ?

**Comment by YueLiao** [comment]
Thanks for your interest. 

The code of target generation is in the dataset folder, e.g. [hico-det](https://github.com/YueLiao/PPDM/blob/master/src/lib/datasets/dataset/hico.py). And the code of main architecture is in the 
 [models folder](https://github.com/YueLiao/PPDM/tree/master/src/lib/models/networks).

**Comment by mahsa1363** [comment]
Thanks for your answer
that's mean is the point matching, displacement and point detection process in the models folder?

**Comment by YueLiao** [comment]
The inference code about Point matching is in [decode.py](https://github.com/YueLiao/PPDM/blob/master/src/lib/models/decode.py)

**Comment by mahsa1363** [comment]
Sorry to bother you so much. I am a beginner
Is decode.py file used for both testing and training in point matching?
Is Point detection part  in target generation in dataset folder e.g. hico-det?

**Comment by YueLiao** [comment]
> Sorry to bother you so much. I am a beginner
> Is decode.py file used for both testing and training in point matching?
> Is Point detection part in target generation in dataset folder e.g. hico-det?

The target generation is in the dataset folder and the main architecture, i.e., backbone and heads are in the model folder, and the matching interaction point with human/object point during inference is in decode.py.

**Comment by mahsa1363** [comment]
thank you very much
