### ISSUE TITLE
vcoco json file and visualizationprogram

### ISSUE THREAD

**Issue by wang-ironman** [YueLiao/PPDM#25]
hello，i wonder if you could upload the vcoco json file and visualization program file. I'd apprecicate it if you could.

**Comment by YueLiao** [comment]
About the annotation files of verb-coco can be seen in #16 and #7. The visualization scripts are not formatted now, and could you provide me an E-mail address where I sent the code?

**Comment by wang-ironman** [comment]
> About the annotation files of verb-coco can be seen in #16 and #7. The visualization scripts are not formatted now, and could you provide me an E-mail address where I sent the code?

1971662@stu.neu.edu.cn        Thank you very much.

**Comment by llrebecca** [comment]
> About the annotation files of verb-coco can be seen in #16 and #7. The visualization scripts are not formatted now, and could you provide me an E-mail address where I sent the code?

Hi, I also want the scripts. [lliu@u.nus.edu](lliu@u.nus.edu) Thanks a lot!

**Comment by YueLiao** [comment]
All above are responded through E-mail.

**Comment by sabhi27** [comment]
Hey @YueLiao, Can you please provide me also your video demo script ?

**Comment by BestSongEver** [comment]
Dear Liao @YueLiao 
I also need the above scrips (e.g., visualization scripts, video demo script)
My E-mail address is 475527783@qq.com
Thanx a lot lot lot.

**Comment by GWwangshuo** [comment]
Dear Liao @YueLiao
Could you please share me with the visualization scripts for vcoco through the email gw.wangshuo@gmail.com?
Thanks a lot.

**Comment by wolfworld6** [comment]
> Dear Liao @YueLiao
> I also need the above scrips (e.g., visualization scripts, video demo script)
> My E-mail address is [475527783@qq.com](mailto:475527783@qq.com)
> Thanx a lot lot lot.

Dear Liao @YueLiao
I also need the above scrips (e.g., visualization scripts, video demo script)
My E-mail address is wolfworld6@126.com)
Thx a lot.

**Comment by YueLiao** [comment]
> > Dear Liao @YueLiao
> > I also need the above scrips (e.g., visualization scripts, video demo script)
> > My E-mail address is [475527783@qq.com](mailto:475527783@qq.com)
> > Thanx a lot lot lot.
> 
> Dear Liao @YueLiao I also need the above scrips (e.g., visualization scripts, video demo script) My E-mail address is [wolfworld6@126.com](mailto:wolfworld6@126.com)) Thx a lot.

In [this issue](https://github.com/YueLiao/PPDM/issues/28)
