### ISSUE TITLE
HOI-A/HOI-W annotation json files

### ISSUE THREAD

**Issue by llrebecca** [YueLiao/PPDM#26]
Hi Yueliao,

I'm running experiments on HOI-A/HOI-W dataset. In the src[ dataset/hoia.py](https://github.com/YueLiao/PPDM/blob/master/src/lib/datasets/dataset/hoia.py) there are two input json files: train_hoia.json, and test_hoia.json. I can't find them in the current repo.

From the PIC [website](http://picdataset.com/challenge/dataset/download/) in the [BaiduDrive](https://pan.baidu.com/s/1iZRC1ybiKJws2RM6_zGYUw), is the 'trainval.json' the file for 'train_hoia.json' in hoia.py? 

And, where is test_hoia.json? Need it to evaluate the test results. I also checked your PIC-HOIW [github](https://github.com/YueLiao/PIC_HOIW), but still cannot find it.

Thank you for your help!

**Comment by YueLiao** [comment]
All the above are responded through E-mail.

**Comment by finngaida** [comment]
Hello, I'm also looking to experiment with the HOI-A dataset, how did you resolve this issue / can you make the files publicly available?

**Comment by YueLiao** [comment]
> Hello, I'm also looking to experiment with the HOI-A dataset, how did you resolve this issue / can you make the files publicly available?

Hi, you can take a look at [issue](https://github.com/YueLiao/PPDM/issues/8) first.

**Comment by finngaida** [comment]
Ah must have missed that. Thanks!
