### ISSUE TITLE
ERROR: cudaRegisterFatBinaryEnd 

### ISSUE THREAD

**Issue by Viky397** [YueLiao/PPDM#27]
Hello!
I am a Masters student trying to run your code for my final project (it looks incredibly interesting)!
However, I am running into an issue when I try to train or test it using your instructions. 
I am on CUDA 9.0, torch==0.4.0, torchvision==0.2.0. However I have tried a mix of the three to no avail.

Upon running, I get the error: ImportError: /home/<user>/PPDM/src/lib/models/networks/DCNv2/_ext/dcn_v2/_dcn_v2.so: undefined symbol: __cudaRegisterFatBinaryEnd

Please do let me know if you have any suggestions to remedy this. Thank you!

**Comment by YueLiao** [comment]
It's Cuda version problem. Use cuda9 and PyTorch 0.4.1 will fix it. More can be referred as the [issue of CenterNet](https://github.com/xingyizhou/CenterNet/issues/67)

**Comment by Viky397** [comment]
Thank you for the reply. I was able to get past that problem. However, when I go to train:
python main.py  hoidet --batch_size 112 --master_batch 7 --lr 4.5e-4 --gpus 1  --num_workers 16  --load_model ../models/ctdet_coco_dla_2x.pth --image_dir images/train2015 --dataset hico --exp_id hoidet_hico_dla

I get the error: RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /pytorch/aten/src/THC/THCGeneral.cpp:70

**Comment by Viky397** [comment]
As well, when I enter --gpus 0, it begins to train, but then the process kills:
```
Starting training...
hoidet/hoidet_hico_dlaKilled
```

**Comment by YueLiao** [comment]
It is too little information to know what happened. Did you turn the batch size small to fit for a single gpu?

**Comment by Viky397** [comment]
Thank you for your comments. I had turned the batch size down but I believe my 1GPU is just not powerful enough.
