### ISSUE TITLE
 how to get a visualized demo (image or video)

### ISSUE THREAD

**Issue by BestSongEver** [YueLiao/PPDM#28]
Thanx for ur great job! @YueLiao 
I am very interested in this work.
I wonder if u can tell me how to get a visualized image demo (e.g., image from HICO, VCOCO, or own image) or video demo?
I would appreciate it if you can provide related scripts.

Best regards

**Comment by YueLiao** [comment]
Thx for your interest in our work, and sorry for the latter response. You can take the below scripts as references. And I am too busy now to format these codes, thus the provided codes may be a bit raw. 

- [video_demo.py](https://gist.github.com/YueLiao/fcea0cc4009fa1f3a5fd70e31886ebff)

- [vis_ui.py](https://gist.github.com/YueLiao/28befa83e554c35568980c95e82cdbac)

- [vis_predictions.py](https://gist.github.com/YueLiao/fb4686eb3233430921fb25b3459ade46)

**Comment by BestSongEver** [comment]
Thanx for your reply.  U are such a kind researcher. @YueLiao 
I will try these scripts latter.

**Comment by LSC333** [comment]
Thank you for these codes in visualized demo! But I noticed a line of code in the *vis_predictions.py* is `prediction = json.load(open('/home/SENSETIME/liaoyue/ly/HOIW/vIs/model_115.json','r'))`. I wonder if you can tell me how to generate the json file?

**Comment by YueLiao** [comment]
> Thank you for these codes in visualized demo! But I noticed a line of code in the _vis_predictions.py_ is `prediction = json.load(open('/home/SENSETIME/liaoyue/ly/HOIW/vIs/model_115.json','r'))`. I wonder if you can tell me how to generate the json file?

The `json' can be generated by the test.py.

**Comment by LSC333** [comment]
> > Thank you for these codes in visualized demo! But I noticed a line of code in the _vis_predictions.py_ is `prediction = json.load(open('/home/SENSETIME/liaoyue/ly/HOIW/vIs/model_115.json','r'))`. I wonder if you can tell me how to generate the json file?
> 
> The 'json' can be generated by the test.py.

thx! The problem is solved!

**Comment by wolfworld6** [comment]
> Thx for your interest in our work, and sorry for the latter response. You can take the below scripts as references. And I am too busy now to format these codes, thus the provided codes may be a bit raw.
> 
> * [video_demo.py](https://gist.github.com/YueLiao/fcea0cc4009fa1f3a5fd70e31886ebff)
> * [vis_ui.py](https://gist.github.com/YueLiao/28befa83e554c35568980c95e82cdbac)
> * [vis_predictions.py](https://gist.github.com/YueLiao/fb4686eb3233430921fb25b3459ade46)

hello,i run the test.py,but i got nothing about the ['bbox']  in  preds[hoi_preds[i]['subject_id']],why?

**Comment by wolfworld6** [comment]
> > Thank you for these codes in visualized demo! But I noticed a line of code in the _vis_predictions.py_ is `prediction = json.load(open('/home/SENSETIME/liaoyue/ly/HOIW/vIs/model_115.json','r'))`. I wonder if you can tell me how to generate the json file?
> 
> The 'json' can be generated by the test.py.

hello,thx for the code,i run the code ,but the output_i has no information about the hoi_preds['rel_point'],why?could tell me?

**Comment by YueLiao** [comment]
> > > Thank you for these codes in visualized demo! But I noticed a line of code in the _vis_predictions.py_ is `prediction = json.load(open('/home/SENSETIME/liaoyue/ly/HOIW/vIs/model_115.json','r'))`. I wonder if you can tell me how to generate the json file?
> > 
> > 
> > The 'json' can be generated by the test.py.
> 
> hello,thx for the code,i run the code ,but the output_i has no information about the hoi_preds['rel_point'],why?could tell me?

The 'rel_point' could be obtained by modifying the [decode file](https://github.com/YueLiao/PPDM/blob/master/src/lib/models/decode.py) through outputting and transforming 'ys_rel, xs_rel'.
