### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by SISTMrL** [YueLiao/PPDM#33]
hello when i run the code, i encounter this problem, cuda9.0 pytorch0.4.1

RuntimeError: cuda runtime error (11) : invalid argument at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp:663

could you give me some suggestions? thanks

**Comment by KaiGaofly** [comment]
hellow ， i encounter the same problem，and i have the cuda9.0 pytorch0.4.1    .
Have you solved this problem?
