### ISSUE TITLE
HOI-A/HOI-W annotation json files

### ISSUE THREAD

**Issue by GWwangshuo** [YueLiao/PPDM#34]
Sorry, I also cannot find the annotation file of **test set** from the HOI-A/HOI-W dataset from [official website](http://picdataset.com/challenge/dataset/HOI-W/) and your provided [link](https://sensetime-my.sharepoint.cn/personal/liaoyue_sensetime_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fliaoyue%5Fsensetime%5Fcom%2FDocuments%2FHOIW%2DDataset&originalPath=aHR0cHM6Ly9zZW5zZXRpbWUtbXkuc2hhcmVwb2ludC5jbi86ZjovZy9wZXJzb25hbC9saWFveXVlX3NlbnNldGltZV9jb20vRWtVQTFzY19zSE5ObVZOaVZzeUY4TDBCQ0U0QVhIYTdzRkViOFlUeDExbGFCZz9ydGltZT0xeDdocXdlcjJFZw). Since I have no chance to access it, I cannot verify PPDM's performance on HOI-A test set. Could you please help me to access this annotation? Thanks a lot.

**Comment by YueLiao** [comment]
Replied by E-mail.

**Comment by MuchHair** [comment]
@YueLiao Hi, I also want to know how to get the test set of HOI-A and the files, i.e. "train_hoia.json" and ""test_hoia.json". Could you tell me that by E-mail? Many thanks.
