### ISSUE TITLE
Question about the verb_name_dict and obj_name_dict for vcoco dataset

### ISSUE THREAD

**Issue by GWwangshuo** [YueLiao/PPDM#36]
Thanks for you great work. I tried to visualize vcoco on your provided [annotations](https://github.com/YueLiao/PPDM/issues/16) by using [PIC_HOIW](https://github.com/YueLiao/PIC_HOIW) tools. However, I cannot access the corresponding **verb_name_dict** and **obj_name_dict**. Could you please share with me them? Thanks a lot.

**Comment by YueLiao** [comment]
Thx for your interest. We did not conduct a visualization on the V-COCO dataset, thus there were no such scripts.

**Comment by GWwangshuo** [comment]
@YueLiao 
I have carefully checked your provided [script ](https://gist.github.com/YueLiao/916a1868c4efeda79477be8cb3f9df59)and the corresponding generated [annotations](https://drive.google.com/drive/folders/1BDY5p590immmcHhAM55rwaRGXdVIuIJ2) and found the `verb_name_dict` is:
`vcoco_verb_dict = {0: "surf_instr", 1: "ski_instr", 2: "cut_instr", 3: "walk", 4: "cut_obj", 5: "ride_instr",
                   6: "talk_on_phone_instr", 7: "kick_obj", 8: "work_on_computer_instr", 9: "eat_obj", 10: "sit_instr",
                   11: "jump_instr", 12: "lay_instr", 13: "drink_instr", 14: "carry_obj", 15: "throw_obj", 16: "eat_instr",
                   17: "smile", 18: "look_obj", 19: "hit_instr", 20: "hit_obj", 21: "snowboard_instr", 22: "run",
                   23: "point_instr", 24: "read_obj", 25: "hold_obj", 26: "skateboard_instr", 27: "stand", 28: "catch_obj"}`

and the `obj_name_dict` is the same as hoi-det dataset.

Moreover, I also found something wrong in your `vcoco_eval.py' in line '93'.
mAP = (mAP - ap[20]) * 25 / 24 

should be 

mAP = (mAP * 25 - ap[20]) / 24

**Comment by YueLiao** [comment]
> @YueLiao
> I have carefully checked your provided [script ](https://gist.github.com/YueLiao/916a1868c4efeda79477be8cb3f9df59)and the corresponding generated [annotations](https://drive.google.com/drive/folders/1BDY5p590immmcHhAM55rwaRGXdVIuIJ2) and found the `verb_name_dict` is:
> `vcoco_verb_dict = {0: "surf_instr", 1: "ski_instr", 2: "cut_instr", 3: "walk", 4: "cut_obj", 5: "ride_instr", 6: "talk_on_phone_instr", 7: "kick_obj", 8: "work_on_computer_instr", 9: "eat_obj", 10: "sit_instr", 11: "jump_instr", 12: "lay_instr", 13: "drink_instr", 14: "carry_obj", 15: "throw_obj", 16: "eat_instr", 17: "smile", 18: "look_obj", 19: "hit_instr", 20: "hit_obj", 21: "snowboard_instr", 22: "run", 23: "point_instr", 24: "read_obj", 25: "hold_obj", 26: "skateboard_instr", 27: "stand", 28: "catch_obj"}`
> 
> and the `obj_name_dict` is the same as hoi-det dataset.
> 
> Moreover, I also found something wrong in your `vcoco_eval.py` in line '93'.
> mAP = (mAP - ap[20]) * 25 / 24
> 
> should be
> 
> mAP = (mAP * 25 - ap[20]) / 24

Thx for your suggestion, and I will correct it soon. If you want to get a satisfactory result in Verb-COCO, it may be a better choice to fix the object detection related weights and only tune the HOI head (interaction point, displacements) due to the very limited training data.
