### ISSUE TITLE
Can you help me to prepare custom dataset?

### ISSUE THREAD

**Issue by Juzz4vijay** [YueLiao/PPDM#4]
I've downloaded HOI dataset.

Depth image : 

![000000](https://user-images.githubusercontent.com/57939625/76943045-b84cc700-6924-11ea-943f-b1718721ca7e.png) 

Label:

![000000](https://user-images.githubusercontent.com/57939625/76943200-f944db80-6924-11ea-84f5-14374507180e.png)

it's look like this..

Is it correct dataset or else can you share me any useful resources.

That would help me to prepare my custom dataset.. 

Thanks in advance..

**Comment by YueLiao** [comment]
You may download the wrong dataset PIC, i.e., another dataset for our relation segmentation dataset. The HOI-W dataset can be downloaded from [Baidu Drive](https://pan.baidu.com/s/1iZRC1ybiKJws2RM6_zGYUw?errno=0&errmsg=Auth%20Login%20Sucess&&bduss=&ssnerror=0&traceid=#list/path=%2F).

**Comment by Juzz4vijay** [comment]
Can you provide me google drive link..

I couldn't access baidu drive. chinese residents only can able to access baidu drive..

I've tried many methods todonload from baidu drive.. all get failed

**Comment by YueLiao** [comment]
I am sorry that I cannot provide the GOOGLE drive link for the HOI-W dataset now due to space limited. For the annotation format, you can take the processed HICO-Det annotation files as a reference, the download link for which has been presented at the readme.
