### ISSUE TITLE
HOI-A/HOI-W annotation json files

### ISSUE THREAD

**Issue by MuchHair** [YueLiao/PPDM#45]
Hi Yueliao,

I'm running experiments on HOI-A/HOI-W dataset. In the src dataset/hoia.py there are two input json files: train_hoia.json, and test_hoia.json. I can't find them in the current repo. Could you tell me that ? 
Thank you for your help!

**Comment by YueLiao** [comment]
Hi,

Thx for your interest. I am sorry that we could not make test_hoia.json in public now, because part of them will be considered as test data on the HOI-W challenge, which will be held in the 3rd PIC workshop on CVPR 2021. Instead, we will open the online evaluation server this or next week.

**Comment by MuchHair** [comment]
> Hi,
> 
> Thx for your interest. I am sorry that we could not make test_hoia.json in public now, because part of them will be considered as test data on the HOI-W challenge, which will be held in the 3rd PIC workshop on CVPR 2021. Instead, we will open the online evaluation server this or next week. Otherwise, I will be glad to help you evaluate it if you are willing to send the result.json to me before the online evaluation openning.

OK. Thanks.
