### ISSUE TITLE
train error caused may be cuda

### ISSUE THREAD

**Issue by JackKoLing** [YueLiao/PPDM#46]
Hi, i try to train the code. And my conda env include: 
**pytorch0.4.1、cudn9.0.176、gcc6、python3.6.12.** and nvcc -v is 9.0 too.
but i also get error "**THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp line=663 error=8 : invalid device function**”  and **RuntimeError: cuda runtime error (8) : invalid device function at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp:663"**
Besides，i try to set batchsize to 1 but not help. If you have some ideas, please tell me. Thank you!!Happy New year.

**Comment by YueLiao** [comment]
Hi, I guess that you install the PyTorch with the wrong CUDA version.

**Comment by JackKoLing** [comment]
> Hi, I guess that you install the PyTorch with the wrong CUDA version.
I install by commend : **conda install pytorch=0.4.1 torchvision -c pytorch.**
And it auto install pytorch0.4.1 and cuda9.0.176. But my GPU is RTX 3070, I always think it has some problem in CUDA.

**Comment by JackKoLing** [comment]
> Hi, I guess that you install the PyTorch with the wrong CUDA version.

I install by commend : conda install pytorch=0.4.1 torchvision -c pytorch.
And it auto install pytorch0.4.1 and cuda9.0.176. But my GPU is RTX 3070, I always think it has some problem in CUDA.

**Comment by YueLiao** [comment]
> > Hi, I guess that you install the PyTorch with the wrong CUDA version.
> 
> I install by commend : conda install pytorch=0.4.1 torchvision -c pytorch.
> And it auto install pytorch0.4.1 and cuda9.0.176. But my GPU is RTX 3070, I always think it has some problem in CUDA.

I think you should install pytorch with "conda install pytorch=0.4.1 cudatoolkit=9.0 torchvision -c pytorch".

**Comment by JackKoLing** [comment]
> > > Hi, I guess that you install the PyTorch with the wrong CUDA version.
> > 
> > 
> > I install by commend : conda install pytorch=0.4.1 torchvision -c pytorch.
> > And it auto install pytorch0.4.1 and cuda9.0.176. But my GPU is RTX 3070, I always think it has some problem in CUDA.
> 
> I think you should install pytorch with "conda install pytorch=0.4.1 cudatoolkit=9.0 torchvision -c pytorch".

I step by your adivces. 
This is my command:
`conda create -n PPDM python=3.6.9 git -y
source activate PPDM
git clone https://github.com/YueLiao/PPDM.git $PPDM_ROOT
conda install pytorch=0.4.1 cudatoolkit=9.0 torchvision -c pytorch
cd PPDM
pip install -r requirements.txt
cd src/lib/models/networks/DCNv2
chmod 777 make.sh
./make.sh   `
However, it still  fail.
![image](https://user-images.githubusercontent.com/30818910/107378129-a4a2e400-6b26-11eb-82dc-d600053a8fa5.png)

**Comment by YueLiao** [comment]
The reason for those problems is clear. Please make sure that:
 
1. You installed the pytorch prebuilt with the same CUDA version as your local installed CUDA (e.g., the one in `/usr/local/cuda`).
2. You compile DCN with the same CUDA version as your runtime.

It is possible that it works well before, and you upgraded pytorch then it broke. If you did not specify the CUDA version when installing pytorch, the default CUDA version can be different for different pytorch versions.

**Comment by JackKoLing** [comment]
> The reason for those problems is clear. Please make sure that:
> 
> 1. You installed the pytorch prebuilt with the same CUDA version as your local installed CUDA (e.g., the one in `/usr/local/cuda`).
> 2. You compile DCN with the same CUDA version as your runtime.
> 
> It is possible that it works well before, and you upgraded pytorch then it broke. If you did not specify the CUDA version when installing pytorch, the default CUDA version can be different for different pytorch versions.

Thank you so much. It's been bothering me for a few days. After several days of checking, it was determined that RTX 3070 does not support CUDA9.0, only CUDA11.0 and above. I switched to a **1080Ti GPU**, configured **gcc-6, g++-6, CUDA 9.0, PyTorch0.4.1**, and finally got running. Thank you again.

**Comment by YueLiao** [comment]
> > The reason for those problems is clear. Please make sure that:
> > 
> > 1. You installed the pytorch prebuilt with the same CUDA version as your local installed CUDA (e.g., the one in `/usr/local/cuda`).
> > 2. You compile DCN with the same CUDA version as your runtime.
> > 
> > It is possible that it works well before, and you upgraded pytorch then it broke. If you did not specify the CUDA version when installing pytorch, the default CUDA version can be different for different pytorch versions.
> 
> Thank you so much. It's been bothering me for a few days. After several days of checking, it was determined that RTX 3070 does not support CUDA9.0, only CUDA11.0 and above. I switched to a **1080Ti GPU**, configured **gcc-6, g++-6, CUDA 9.0, PyTorch0.4.1**, and finally got running. Thank you again.

I also implement a pytorch 1.0+ with CUDA 10.1 version on pt1 branch.

**Comment by JackKoLing** [comment]
> > > The reason for those problems is clear. Please make sure that:
> > > 
> > > 1. You installed the pytorch prebuilt with the same CUDA version as your local installed CUDA (e.g., the one in `/usr/local/cuda`).
> > > 2. You compile DCN with the same CUDA version as your runtime.
> > > 
> > > It is possible that it works well before, and you upgraded pytorch then it broke. If you did not specify the CUDA version when installing pytorch, the default CUDA version can be different for different pytorch versions.
> > 
> > 
> > Thank you so much. It's been bothering me for a few days. After several days of checking, it was determined that RTX 3070 does not support CUDA9.0, only CUDA11.0 and above. I switched to a **1080Ti GPU**, configured **gcc-6, g++-6, CUDA 9.0, PyTorch0.4.1**, and finally got running. Thank you again.
> 
> I also implement a pytorch 1.0+ with CUDA 10.1 version on pt1 branch.

very good job
