### ISSUE TITLE
what are the differences between model_last and model_best?

### ISSUE THREAD

**Issue by WXLL579** [YueLiao/PPDM#52]
hello, I have run the code on model_best of hourglass, but the mAP obtained by this model_best is 0.0，and model_last can be used to get a mAP more than 15.  And also , the prediction results of the models obtained in the training process are all empty, and the sizes of these models are all 2.18G. Thanks very much for your answer and your excellent idea. 

The error of testing the trained model:

File "test_hoi.py", line 114, in <module>
    prefetch_test(opt)
  File "test_hoi.py", line 99, in prefetch_test
    map = hoi_eval.evalution(output_hoi)
  File "/home/ll579/PPDM_/src_/lib/eval/hico_eval.py", line 66, in evalution
    bbox_pairs, bbox_ov = self.compute_iou_mat(gt_bbox, pred_bbox)
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by WXLL579** [comment]
it seems  that the model of 232.46MB can be used correctly

**Comment by YueLiao** [comment]
I have checked these two models, both of which are 2.0GB. Otherwise, 15.0 mAP is also incorrect. 

This error is caused by failing to load a checkpoint during inference.

**Comment by WXLL579** [comment]
thanks!
