### ISSUE TITLE
dataset annotations

### ISSUE THREAD

**Issue by mytk2012** [YueLiao/PPDM#53]
Professor，can you give a brief introduction of annotations like(test_hico.json,trainval_hico.json,corre_hico.npy)?In test_hico.json,there are no introductions about subject_id、category_id and object_id.This confuses me.No map between .id and name was introduced

**Comment by YueLiao** [comment]
Thx for your interest in our repo. The answers to your mentioned problems can be found in similar issues #17 and #12.

**Comment by mytk2012** [comment]
Thank you，I have finished transforming this.
