### ISSUE TITLE
question about equation 5 in the paper

### ISSUE THREAD

**Issue by Senwang98** [YueLiao/PPDM#54]
Hi, @YueLiao @ZhiyuanChen 
I feel confused about equation 5 in the paper,
![image](https://user-images.githubusercontent.com/23122139/128481755-1a31aa74-436d-4246-a42f-60d7290ea1a6.png)
It seem to be 0 in the equation all the time. If misunderstand, can you tell me what the meaning of equation 5?

**Comment by YueLiao** [comment]
I am confused by your issue, why do you think it seems to be 0 in the equation all the time?

**Comment by Senwang98** [comment]
抱歉打扰，我认为应该是我个人理解的问题而非论文的问题，所以想请教一下。
这边的x^a应该是固定的，这个公式里面的displacement插值不应该是x^a与x^h的之间的插值吗，我从Displacement loss这一节中获悉了其含义：
![image](https://user-images.githubusercontent.com/23122139/128631138-7c308da0-2168-4ae1-8c11-dd07b30733a0.png)
如果是这样的话展开好像是0

**Comment by YueLiao** [comment]
loss function只是一个优化目标，网络预测出来的结果不可能完全可以拟合到预测目标。这个公式的意义是要找到离“预测出的action point减去预测出来的offset”最近且“具有较高置信度”的人或物的中心点。

**Comment by Senwang98** [comment]
@YueLiao 
好的，这里的d(x^a,y^a)这个式子其实就是两层特征图上面的预测偏移量？
预测的交互点减去预测偏移量之后得到的是人的中心点，但是这个中心点跟直接通过heatmap的预测点不是完全相同的（一个直接预测，一个间接预测）？
谢谢学长了，一直钻牛角尖非要展开这个d符号
