### ISSUE TITLE
no code here?

### ISSUE THREAD

**Issue by mytk2012** [YueLiao/PPDM#56]

**Comment by YueLiao** [comment]
Sorry，I cannot get your point.

**Comment by mytk2012** [comment]
Py(main.py) file has been missing.

**Comment by YueLiao** [comment]
all codes in src folder~

**Comment by mytk2012** [comment]
Thanks! Can you give me suggestions on HOI projects which is with visualization tools?

**Comment by YueLiao** [comment]
You may take this [repo](https://github.com/YueLiao/PIC_HOIW) as a reference.

**Comment by mytk2012** [comment]
So kind are you, and if convenient, can you leave mail? I have succeeded in transforming my dataset and checked it in qpic project successfully when training. But when i applied in HoiTransformer, it reports serveral errors, and it seems that the index label has been out of bounds. Both these projects apply the same annotations. It confused me.

**Comment by YueLiao** [comment]
This is because QPIC follows our data annotation format, but HoiTransformer may be slightly different. So this question is better to be turned to the HoiTransformer.

**Comment by mytk2012** [comment]
Does your research group still recruit PhDs? I wanna have a try.
