### ISSUE TITLE
undefined symbol: __cudaRegisterFatBinaryEnd Issue

### ISSUE THREAD

**Issue by mansooreh1** [YueLiao/PPDM#59]
Hello
 I have cuda 7.5 but I get the following error"undefined symbol: __cudaRegisterFatBinaryEnd Issue" when run python main.py  Hoidet --batch_size 112 --master_batch 7 --lr 4.5e-4 --gpus 0,1,2,3,4,5,6,7  --num_workers 16  --load_model ../models/ctdet_coco_dla_2x.pth --image_dir images/train2015 --dataset hico --exp_id hoidet_hico_dla

**Comment by YueLiao** [comment]
Please use CUDA 9.0~

**Comment by mansooreh1** [comment]
Thanks. I have cuda version 7.0, how can I run the program without changing the version?

**Comment by YueLiao** [comment]
Cuda 7.0 Unsupported.
