### ISSUE TITLE
test for hoia

### ISSUE THREAD

**Issue by WXLL579** [YueLiao/PPDM#61]
Hello! Thx for your work! Could you publicly the test code of hoi-a dataset now? The challenge seems has already closed.

**Comment by YueLiao** [comment]
The test code is generally the same as the HICO-Det, and such codes have been already provided in the original project, e.g., the HOI-A data loader. However, our experiments were conducted on the very initial HOI-A dataset, so implementation with the current HOI-A dataset may lead to a different performance from the paper reported.

**Comment by WXLL579** [comment]
ok, thanks!
