### ISSUE TITLE
About Heatmaps

### ISSUE THREAD

**Issue by iostream1000** [YueLiao/PPDM#62]
Hello, I noticed that the point location loss in Section 3.2 of your paper mentioned that three heatmaps are produced by adding three respective convolutional blocks. However, it seems that the human point heatmap and the object point heatmap in your code are generated from one convolutional block. Is there something wrong with my understanding?

**Comment by YueLiao** [comment]
Hi, you are right. The initial version of the released code is implemented with the human and object two-branches style. However, we find that combining human and object detection into a single branch can achieve similar performance and few computation costs through experiments. Therefore, we modify and refine this setting.

**Comment by iostream1000** [comment]
Thanks for your reply. Please close it.
