### ISSUE TITLE
Questions about code and dataset

### ISSUE THREAD

**Issue by SherlockHolmes221** [YueLiao/PPDM#7]
1. PPDM achieves high mAP in HICO and HOI-A dataset which are both big dataset, what about the performance on small dataset like v-coco?
2. What is the effect of the affine_transform when producing labeled heatmap?
Thanks

**Comment by YueLiao** [comment]
1. We only evaluate our PPDM based on our rewriting evaluation script for V-COCO. Hourglass-104 achieved about 59. 
2. Because we follow Objects as points to apply a data augmentation during training, the affine_transform function is used to generate the corresponding GT heatmap for the transformed input, e.g., scale crop aug,  flip etc.

**Comment by SherlockHolmes221** [comment]
The v-coco mAP is the same with the official one?

**Comment by YueLiao** [comment]
We do not make sure it. We haven't conducted the evaluation in the official one.  Its work is in the to-do list but not now, may next month.  You can try it by yourself, and we have provided the corresponding training code for vcoco.

**Comment by SherlockHolmes221** [comment]
Thanks, closing it

**Comment by SherlockHolmes221** [comment]
> 1. We only evaluate our PPDM based on our rewriting evaluation script for V-COCO. Hourglass-104 achieved about 59.
> 2. Because we follow Objects as points to apply a data augmentation during training, the affine_transform function is used to generate the corresponding GT heatmap for the transformed input, e.g., scale crop aug,  flip etc.

Could you share vcoco(Hourglass-104) training scripts or hyperparameters ? I tried but can not reach 59.

**Comment by YueLiao** [comment]
All hyper-parameters are the same as hico-det's. Additionally, we only conduct an evaluation based on the non-official evolutional script, which cannot be compared to the methods evaluated by the official script.

**Comment by SherlockHolmes221** [comment]
Thanks

**Comment by SherlockHolmes221** [comment]
> All hyper-parameters are the same as hico-det's. Additionally, we only conduct an evaluation based on the non-official evolutional script, which cannot be compared to the methods evaluated by the official script.

It is weird that I use the same hyper-parameters(lr3e-4 bs 31) in hico-det's training scripts to train vcoco, but still can not reach 59 using your vcoco_eval.py test script. I just get about 54.

**Comment by YueLiao** [comment]
> > All hyper-parameters are the same as hico-det's. Additionally, we only conduct an evaluation based on the non-official evolutional script, which cannot be compared to the methods evaluated by the official script.
> 
> It is weird that I use the same hyper-parameters(lr3e-4 bs 31) in hico-det's training scripts to train vcoco, but still can not reach 59 using your vcoco_eval.py test script. I just get about 54.

I try to find the checkpoint, but I found all of them are deleted due to the space limitation. The 59 is got by the older version code, and you can try it based on this [repo](https://github.com/YueLiao/PPDM/tree/9a0677b7583c6b6ce5e0488ff8b41f194fd95e70). Hope you can reproduce it.

**Comment by YueLiao** [comment]
> > > All hyper-parameters are the same as hico-det's. Additionally, we only conduct an evaluation based on the non-official evolutional script, which cannot be compared to the methods evaluated by the official script.
> > 
> > 
> > It is weird that I use the same hyper-parameters(lr3e-4 bs 31) in hico-det's training scripts to train vcoco, but still can not reach 59 using your vcoco_eval.py test script. I just get about 54.
> 
> I try to find the checkpoint, but I found all of them are deleted due to the space limitation. The 59 is got by the older version code, and you can try it based on this [repo](https://github.com/YueLiao/PPDM/tree/9a0677b7583c6b6ce5e0488ff8b41f194fd95e70). Hope you can reproduce it.

Aha, I have just found the checkpoint, OneDrive or BaiduDrive? The only preserved one. However, I don't think the current training and test strategy is not fit for the official vcoco evaluation method. It may be better to give a threshold to remove the non-interaction predictions or to take the non-interaction images into training.

**Comment by SherlockHolmes221** [comment]
Thanks, both OneDrive and BaiduDrive is ok

**Comment by YueLiao** [comment]
> Thanks, both OneDrive and BaiduDrive is ok

[OneDrive](https://sensetime-my.sharepoint.cn/:u:/g/personal/liaoyue_sensetime_com/EQwm5L-K11VGrro1GjJLEccBsC5tkvws2M3WwkNDJxB34w?e=49o28a).
