### ISSUE TITLE
Inference time on the HICO-Det test set

### ISSUE THREAD

**Issue by Pursue26** [YueLiao/PPDM#9]
Excuse me, 
1. how is the inference time calculated on the iCAN / TIN, including which parts of the inference time (if divided into pre-processing, HOI inference , post-processing) ? 
2. and, for iCAN, do you use the test code of iCAN to calculate the inference time? thanks.

**Comment by YueLiao** [comment]
For two-stage methods, e.g., iCAN/TIN, we calculated the inference time including the human/object detection and HOI prediction, if using additional human pose features, we will add the inference time spent by the pose estimator (more details can be seen in our paper).  

The inference time presented in the paper from running the open-source test code or get the inference time from the authors directly. 

The inference time provided by the test code of iCAN only calculated the process of HOI prediction without human/object detection.

**Comment by Pursue26** [comment]
Thank you, I have read your paper, for iCAN in the table 2, your inference time is '92 + 112 = 204' (ms), i guess '92' is the human/object detection time, '112' is the HOI prediction time, am I right ?
2. if right, i think iCAN is related to the number of humans(N) and objects(M), is your ‘112’ the average of HOI prediction for iCAN ?
3. if right, in another paper I read (Classifying All Interacting Pairs in a Single Shot), iCAN's inference time is like this : **from less than 1 second to more than 30 seconds** 
![image](https://user-images.githubusercontent.com/49673141/78450982-229b9080-76b5-11ea-944a-9770f21f62d3.png)
Why is the iCAN recorded in your paper millisecond level, i'm confused. Sure, your job is really great.

**Comment by YueLiao** [comment]
The inference speed reported in our paper for iCAN is the average time of all images (112ms/image) in test set of HICO-DET where we ran the official test code of iCAN on single Titan XP. Additionally, iCAN also reported the inference speed for VCOCO  in Table 3c of the paper, which is similar to 112ms. 
![image](https://user-images.githubusercontent.com/30544357/78467109-dc3d4480-773b-11ea-89bf-70331e739cf3.png)
